server:
  port: ${SERVER_PORT:8089} #used as a port set in env variables
logging:
  level:
    org.springframework.security: DEBUG
spring:
  datasource:
    url: database_url
    username: username
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update